GET http://localhost:8080/contacts

###

GET http://localhost:8080/contacts?id=68d5a9b7255b77013e21b172

###

GET http://localhost:8080/contacts?id=68d5aa9b255b77013e21b173

###

GET http://localhost:8080/contacts?id=68d5ab1d255b77013e21b174

###
GET https://cse341-bh1k.onrender.com/contacts

###

GET https://cse341-bh1k.onrender.com/contacts?id=68d5a9b7255b77013e21b172

###

GET https://cse341-bh1k.onrender.com/contacts?id=68d5aa9b255b77013e21b173

###

GET https://cse341-bh1k.onrender.com/contacts?id=68d5ab1d255b77013e21b174

###

# Create a new contact 
POST http://localhost:8080/contacts/
Content-Type: application/json

{
	"firstName": "Doctor",
	"lastName": "Example",
	"email": "drexample@mail.com",
	"favoriteColor": "White",
	"birthday": "2024-01-02"
}

###

POST https://cse341-bh1k.onrender.com/contacts
Content-Type: application/json

{
	"firstName": "Doctor",
	"lastName": "Example",
	"email": "drexample@mail.com",
	"favoriteColor": "White",
	"birthday": "2024-01-02"
}

###

# Update :id
PUT http://localhost:8080/contacts/68ded946e08512f8697ee224
Content-Type: application/json

{
	"firstName": "Mister",
	"lastName": "Example",
	"email": "mrexample@mail.com",
	"favoriteColor": "Black",
	"birthday": "1327-11-10"
}

###

PUT https://cse341-bh1k.onrender.com/contacts/68ded3d61aa23f35c7a3363c
Content-Type: application/json

{
	"firstName": "Grace",
	"lastName": "Hopper",
	"email": "grace.hopper@example.com",
	"favoriteColor": "Navy",
	"birthday": "1906-12-09"
}

###

# DELETE a contact by id
DELETE http://localhost:8080/contacts/68ded9faa51cb5ee095e79d3

###

DELETE https://cse341-bh1k.onrender.com/contacts/:id
