GET http://localhost:8080/contacts

###

GET http://localhost:8080/contacts?id=68d5a9b7255b77013e21b172

###

GET http://localhost:8080/contacts?id=68d5aa9b255b77013e21b173

###

GET http://localhost:8080/contacts?id=68d5ab1d255b77013e21b174

###
GET https://cse341-bh1k.onrender.com/contacts

###

GET https://cse341-bh1k.onrender.com/contacts?id=68d5a9b7255b77013e21b172

###

GET https://cse341-bh1k.onrender.com/contacts?id=68d5aa9b255b77013e21b173

###

GET https://cse341-bh1k.onrender.com/contacts?id=68d5ab1d255b77013e21b174

###

# Create a new contact 
POST http://localhost:8080/contacts
Content-Type: application/json

{
	"firstName": "Ada",
	"lastName": "Sterling",
	"email": "ada@example.com",
	"favoriteColor": "Teal",
	"birthday": "1815-12-10"
}

###

POST https://cse341-bh1k.onrender.com/contacts
Content-Type: application/json

{
	"firstName": "Grace",
	"lastName": "Hopper",
	"email": "grace@example.com",
	"favoriteColor": "Navy",
	"birthday": "1906-12-09"
}

###

# Replace :id
PUT http://localhost:8080/contacts/68ded731e08512f8697ee221
Content-Type: application/json

{
	"firstName": "Another one?",
	"lastName": "Test",
	"email": "mrtestguy@mail.com",
	"favoriteColor": "Rainbow",
	"birthday": "1327-11-10"
}

###

PUT https://cse341-bh1k.onrender.com/contacts/68ded3d61aa23f35c7a3363c
Content-Type: application/json

{
	"firstName": "Grace",
	"lastName": "Hopper",
	"email": "grace.hopper@example.com",
	"favoriteColor": "Navy",
	"birthday": "1906-12-09"
}

###

# DELETE a contact by id
DELETE http://localhost:8080/contacts/68ded731e08512f8697ee221

###

DELETE https://cse341-bh1k.onrender.com/contacts/:id
